import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs'
import { join, basename, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const HEADER_CSS = '/* GENERATED by ds/tokens/build.mjs — do not edit */'
const HEADER_TS = '// GENERATED by ds/tokens/build.mjs — do not edit'
const SEMANTIC_NAMESPACES = ['color', 'radius', 'type', 'density', 'motion', 'shadow']
const SKIN_STORAGE_KEY_VALUE = 'portfolio:skin'
const MOTION_STORAGE_KEY_VALUE = 'portfolio:motion'

const __filename = fileURLToPath(import.meta.url)
const __dir = dirname(__filename)

// Default paths: tokens dir is this file's directory; fonts dir is app/frontend/assets/fonts/
const DEFAULT_TOKENS_DIR = __dir
const DEFAULT_OUT_DIR = join(__dir, 'generated')
const DEFAULT_FONTS_DIR = join(__dir, '../../assets/fonts')

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function isKebabCase(key) {
  return /^[a-z0-9]+(-[a-z0-9]+)*$/.test(key)
}

function resolveRefs(value) {
  return String(value).replace(
    /\{raw\.([^.}]+)\.([^}]+)\}/g,
    (_, group, key) => `var(--raw-${group}-${key})`,
  )
}

function getRawRefs(value) {
  const refs = []
  for (const [, group, key] of String(value).matchAll(/\{raw\.([^.}]+)\.([^}]+)\}/g)) {
    refs.push(`${group}.${key}`)
  }
  return refs
}

function escapeTs(s) {
  // escape backslashes first, then single quotes
  return String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export function buildTokens({ tokensDir, outDir, fontsDir } = {}) {
  const _tokensDir = tokensDir ?? DEFAULT_TOKENS_DIR
  const _outDir = outDir ?? DEFAULT_OUT_DIR
  const _fontsDir = fontsDir ?? DEFAULT_FONTS_DIR

  const errors = []
  const warnings = []

  // ── Load files ─────────────────────────────────────────────────────────────

  let allEntries
  try {
    allEntries = readdirSync(_tokensDir, { withFileTypes: true })
  } catch (e) {
    throw new Error(`Cannot read tokensDir '${_tokensDir}': ${e.message}`)
  }

  // Only top-level *.tokens.json files (subdirs are safe for test fixtures)
  const tokenFiles = allEntries
    .filter((d) => d.isFile() && d.name.endsWith('.tokens.json'))
    .map((d) => d.name)

  const BASE_FILE = 'base.tokens.json'
  if (!tokenFiles.includes(BASE_FILE)) {
    throw new Error('Token validation failed:\n\n  1. Missing base.tokens.json')
  }

  let base
  try {
    base = JSON.parse(readFileSync(join(_tokensDir, BASE_FILE), 'utf8'))
  } catch (e) {
    throw new Error(`Cannot parse ${BASE_FILE}: ${e.message}`)
  }

  const skinFiles = tokenFiles.filter((f) => f !== BASE_FILE).sort()

  if (skinFiles.length === 0) {
    throw new Error(
      'Token validation failed:\n\n  1. No skin files found (expected <name>.tokens.json alongside base.tokens.json)',
    )
  }

  const skins = []
  for (const file of skinFiles) {
    try {
      const data = JSON.parse(readFileSync(join(_tokensDir, file), 'utf8'))
      const stem = basename(file, '.tokens.json')
      skins.push({ file, stem, data })
    } catch (e) {
      errors.push(`Cannot parse ${file}: ${e.message}`)
    }
  }

  if (errors.length > 0) {
    throw new Error(
      'Token validation failed:\n\n' + errors.map((e, i) => `  ${i + 1}. ${e}`).join('\n'),
    )
  }

  // ── Validate base ──────────────────────────────────────────────────────────

  for (const [topKey, group] of Object.entries(base)) {
    if (!isKebabCase(topKey)) {
      errors.push(`${BASE_FILE}: top-level key '${topKey}' is not kebab-case`)
    }
    if (group && typeof group === 'object') {
      for (const [key, value] of Object.entries(group)) {
        if (!isKebabCase(key)) {
          errors.push(`${BASE_FILE}: ${topKey} key '${key}' is not kebab-case`)
        }
        if (typeof value === 'string' && /\{[^}]+\}/.test(value)) {
          errors.push(
            `${BASE_FILE}: ${topKey}.${key} — value contains a ref (base values must be literals)`,
          )
        }
      }
    }
  }

  // ── Validate each skin ─────────────────────────────────────────────────────

  let defaultCount = 0

  for (const { file, stem, data } of skins) {
    const meta = data.meta
    if (!meta || typeof meta !== 'object') {
      errors.push(`${file}: missing 'meta' object`)
      continue
    }

    // meta.name must match filename stem (and be kebab-case)
    if (meta.name !== stem) {
      errors.push(`${file}: meta.name '${meta.name}' must match filename stem '${stem}'`)
    }
    if (meta.name && !isKebabCase(meta.name)) {
      errors.push(`${file}: meta.name '${meta.name}' is not kebab-case`)
    }

    // colorScheme
    if (!['light', 'dark'].includes(meta.colorScheme)) {
      errors.push(`${file}: meta.colorScheme '${meta.colorScheme}' must be 'light' or 'dark'`)
    }

    // default flag
    if (meta.default === true) defaultCount++

    // font entries
    if (Array.isArray(meta.fonts)) {
      for (let i = 0; i < meta.fonts.length; i++) {
        const font = meta.fonts[i]
        for (const field of ['family', 'file', 'weight', 'style', 'display']) {
          if (!font[field]) {
            errors.push(`${file}: fonts[${i}] missing required field '${field}'`)
          }
        }
        if (font.file && !existsSync(join(_fontsDir, font.file))) {
          errors.push(`${file}: fonts[${i}].file '${font.file}' not found in ${_fontsDir}`)
        }
      }
    }

    // raw: group names + keys must be kebab-case; values must not contain refs
    const raw = data.raw ?? {}
    for (const [group, keys] of Object.entries(raw)) {
      if (!isKebabCase(group)) {
        errors.push(`${file}: raw group '${group}' is not kebab-case`)
      }
      if (keys && typeof keys === 'object') {
        for (const [key, value] of Object.entries(keys)) {
          if (!isKebabCase(key)) {
            errors.push(`${file}: raw.${group} key '${key}' is not kebab-case`)
          }
          if (typeof value === 'string' && /\{[^}]+\}/.test(value)) {
            errors.push(
              `${file}: raw.${group}.${key} — value contains a ref (raw values must be literals)`,
            )
          }
        }
      }
    }

    // semantic: exactly the six namespaces; keys must be kebab-case
    const semantic = data.semantic ?? {}
    const actualNs = new Set(Object.keys(semantic))

    for (const ns of SEMANTIC_NAMESPACES) {
      if (!actualNs.has(ns)) errors.push(`${file}: missing semantic namespace '${ns}'`)
    }
    for (const ns of actualNs) {
      if (!SEMANTIC_NAMESPACES.includes(ns)) {
        errors.push(
          `${file}: extra semantic namespace '${ns}' (allowed: ${SEMANTIC_NAMESPACES.join(', ')})`,
        )
      }
    }
    for (const [ns, tokens] of Object.entries(semantic)) {
      if (tokens && typeof tokens === 'object') {
        for (const key of Object.keys(tokens)) {
          if (!isKebabCase(key)) {
            errors.push(`${file}: semantic.${ns} key '${key}' is not kebab-case`)
          }
        }
      }
    }

    // ref resolution: every {raw.X.Y} must resolve within this skin's raw
    for (const [ns, tokens] of Object.entries(semantic)) {
      if (!tokens || typeof tokens !== 'object') continue
      for (const [key, value] of Object.entries(tokens)) {
        for (const ref of getRawRefs(value)) {
          const dotIdx = ref.indexOf('.')
          const group = ref.slice(0, dotIdx)
          const rawKey = ref.slice(dotIdx + 1)
          if (!raw[group]) {
            errors.push(
              `${file}: semantic.${ns}.${key} references unknown raw group '${group}' (ref: {raw.${group}.${rawKey}})`,
            )
          } else if (raw[group][rawKey] === undefined) {
            errors.push(
              `${file}: semantic.${ns}.${key} references unknown raw key '${rawKey}' in '${group}' (ref: {raw.${group}.${rawKey}})`,
            )
          }
        }
      }
    }

    // zones: scoped re-assignments of a subset of this skin's semantic keys
    const zones = data.zones ?? {}
    for (const [zoneName, zone] of Object.entries(zones)) {
      if (!isKebabCase(zoneName)) {
        errors.push(`${file}: zone '${zoneName}' is not kebab-case`)
      }
      if (!zone || typeof zone !== 'object') {
        errors.push(`${file}: zone '${zoneName}' must be an object`)
        continue
      }
      if (!['light', 'dark'].includes(zone.colorScheme)) {
        errors.push(
          `${file}: zones.${zoneName}.colorScheme '${zone.colorScheme}' must be 'light' or 'dark'`,
        )
      }
      const zoneTokens = zone.tokens ?? {}
      for (const [ns, tokens] of Object.entries(zoneTokens)) {
        if (!SEMANTIC_NAMESPACES.includes(ns)) {
          errors.push(
            `${file}: zones.${zoneName} has namespace '${ns}' (allowed: ${SEMANTIC_NAMESPACES.join(', ')})`,
          )
          continue
        }
        if (!tokens || typeof tokens !== 'object') continue
        for (const [key, value] of Object.entries(tokens)) {
          if (!isKebabCase(key)) {
            errors.push(`${file}: zones.${zoneName}.${ns} key '${key}' is not kebab-case`)
          }
          if (semantic[ns]?.[key] === undefined) {
            errors.push(
              `${file}: zones.${zoneName}.${ns}.${key} does not exist in semantic.${ns} (zones may only re-assign existing semantic keys)`,
            )
          }
          for (const ref of getRawRefs(value)) {
            const dotIdx = ref.indexOf('.')
            const group = ref.slice(0, dotIdx)
            const rawKey = ref.slice(dotIdx + 1)
            if (!raw[group] || raw[group][rawKey] === undefined) {
              errors.push(
                `${file}: zones.${zoneName}.${ns}.${key} references unknown raw key (ref: {raw.${group}.${rawKey}})`,
              )
            }
          }
        }
      }
    }
  }

  // ── Parity: identical semantic key sets across all skins ───────────────────

  if (skins.length > 1) {
    const ref = skins[0]
    for (const ns of SEMANTIC_NAMESPACES) {
      const refKeys = new Set(Object.keys(ref.data.semantic?.[ns] ?? {}))
      for (const { file, data } of skins.slice(1)) {
        const skinKeys = new Set(Object.keys(data.semantic?.[ns] ?? {}))
        for (const key of refKeys) {
          if (!skinKeys.has(key)) {
            errors.push(`${file}: semantic.${ns} missing key '${key}' (present in ${ref.file})`)
          }
        }
        for (const key of skinKeys) {
          if (!refKeys.has(key)) {
            errors.push(`${file}: semantic.${ns} has extra key '${key}' (not in ${ref.file})`)
          }
        }
      }
    }
  }

  // ── Parity: identical zone names and per-zone key sets across all skins ────

  if (skins.length > 1) {
    const ref = skins[0]
    const refZones = ref.data.zones ?? {}
    const refZoneNames = new Set(Object.keys(refZones))
    for (const { file, data } of skins.slice(1)) {
      const skinZones = data.zones ?? {}
      const skinZoneNames = new Set(Object.keys(skinZones))
      for (const name of refZoneNames) {
        if (!skinZoneNames.has(name)) {
          errors.push(`${file}: missing zone '${name}' (present in ${ref.file})`)
        }
      }
      for (const name of skinZoneNames) {
        if (!refZoneNames.has(name)) {
          errors.push(`${file}: has extra zone '${name}' (not in ${ref.file})`)
        }
      }
      for (const name of refZoneNames) {
        if (!skinZoneNames.has(name)) continue
        for (const ns of SEMANTIC_NAMESPACES) {
          const refKeys = new Set(Object.keys(refZones[name]?.tokens?.[ns] ?? {}))
          const skinKeys = new Set(Object.keys(skinZones[name]?.tokens?.[ns] ?? {}))
          for (const key of refKeys) {
            if (!skinKeys.has(key)) {
              errors.push(
                `${file}: zones.${name}.${ns} missing key '${key}' (present in ${ref.file})`,
              )
            }
          }
          for (const key of skinKeys) {
            if (!refKeys.has(key)) {
              errors.push(
                `${file}: zones.${name}.${ns} has extra key '${key}' (not in ${ref.file})`,
              )
            }
          }
        }
      }
    }
  }

  // ── Exactly one default ────────────────────────────────────────────────────

  if (defaultCount === 0) {
    errors.push('No skin has default: true — exactly one skin must be the default')
  } else if (defaultCount > 1) {
    errors.push(`${defaultCount} skins have default: true — exactly one skin must be the default`)
  }

  // ── Aggregate and throw ────────────────────────────────────────────────────

  if (errors.length > 0) {
    throw new Error(
      'Token validation failed:\n\n' + errors.map((e, i) => `  ${i + 1}. ${e}`).join('\n'),
    )
  }

  // ── Warnings: unreferenced raw keys ───────────────────────────────────────

  for (const { file, data } of skins) {
    const raw = data.raw ?? {}
    const refs = new Set()
    for (const tokens of Object.values(data.semantic ?? {})) {
      for (const value of Object.values(tokens)) {
        for (const ref of getRawRefs(value)) refs.add(ref)
      }
    }
    for (const zone of Object.values(data.zones ?? {})) {
      for (const tokens of Object.values(zone.tokens ?? {})) {
        for (const value of Object.values(tokens)) {
          for (const ref of getRawRefs(value)) refs.add(ref)
        }
      }
    }
    for (const [group, keys] of Object.entries(raw)) {
      for (const key of Object.keys(keys)) {
        if (!refs.has(`${group}.${key}`)) {
          warnings.push(`${file}: raw.${group}.${key} is never referenced by any semantic value`)
        }
      }
    }
  }

  // ── Prepare ordered skins: default first, then alphabetical ───────────────

  const defaultEntry = skins.find((s) => s.data.meta.default === true)
  const nonDefaults = skins
    .filter((s) => s.data.meta.default !== true)
    .sort((a, b) => a.stem.localeCompare(b.stem))
  const ordered = [defaultEntry, ...nonDefaults]

  // ── Create output directory ────────────────────────────────────────────────

  mkdirSync(_outDir, { recursive: true })

  const writtenFiles = []
  function write(name, content) {
    const p = join(_outDir, name)
    writeFileSync(p, content, 'utf8')
    writtenFiles.push(p)
  }

  // ── base.css ───────────────────────────────────────────────────────────────

  {
    const lines = [HEADER_CSS, ':root {']
    for (const [key, value] of Object.entries(base.space ?? {})) {
      lines.push(`  --space-${key}: ${value};`)
    }
    for (const [key, value] of Object.entries(base.z ?? {})) {
      lines.push(`  --z-${key}: ${value};`)
    }
    lines.push('}', '')
    write('base.css', lines.join('\n'))
  }

  // ── skin-<name>.css ────────────────────────────────────────────────────────

  for (const { stem, data } of ordered) {
    const lines = [HEADER_CSS, `[data-skin='${stem}'] {`]
    lines.push(`  color-scheme: ${data.meta.colorScheme};`)
    // raw tokens (group insertion order, then key insertion order)
    for (const [group, keys] of Object.entries(data.raw ?? {})) {
      for (const [key, value] of Object.entries(keys)) {
        lines.push(`  --raw-${group}-${key}: ${value};`)
      }
    }
    // semantic tokens (namespace insertion order, then key insertion order)
    for (const [ns, tokens] of Object.entries(data.semantic ?? {})) {
      for (const [key, value] of Object.entries(tokens)) {
        lines.push(`  --${ns}-${key}: ${resolveRefs(value)};`)
      }
    }
    lines.push('}')
    // zones: scoped re-assignments of the same semantic custom properties
    for (const [zoneName, zone] of Object.entries(data.zones ?? {})) {
      lines.push('')
      lines.push(
        `[data-skin='${stem}'] [data-zone='${zoneName}'],`,
        `[data-skin='${stem}'][data-zone='${zoneName}'] {`,
      )
      lines.push(`  color-scheme: ${zone.colorScheme};`)
      for (const [ns, tokens] of Object.entries(zone.tokens ?? {})) {
        for (const [key, value] of Object.entries(tokens)) {
          lines.push(`  --${ns}-${key}: ${resolveRefs(value)};`)
        }
      }
      lines.push('}')
    }
    lines.push('')
    write(`skin-${stem}.css`, lines.join('\n'))
  }

  // ── fonts.css ─────────────────────────────────────────────────────────────

  {
    const lines = [HEADER_CSS]
    const seen = new Set()
    const entries = []
    for (const { data } of ordered) {
      for (const font of data.meta.fonts ?? []) {
        const key = `${font.family}|${font.file}|${font.weight}|${font.style}`
        if (!seen.has(key)) {
          seen.add(key)
          entries.push(font)
        }
      }
    }
    for (const font of entries) {
      if (lines.length > 1) lines.push('')
      lines.push('@font-face {')
      lines.push(`  font-family: '${font.family}';`)
      lines.push(`  src: url('../../../assets/fonts/${font.file}') format('woff2');`)
      lines.push(`  font-weight: ${font.weight};`)
      lines.push(`  font-style: ${font.style};`)
      lines.push(`  font-display: ${font.display};`)
      lines.push('}')
    }
    lines.push('')
    write('fonts.css', lines.join('\n'))
  }

  // ── motion-overrides.css ──────────────────────────────────────────────────

  {
    const motionTokens = defaultEntry.data.semantic.motion ?? {}
    const durationKeys = Object.keys(motionTokens).filter((k) => k.startsWith('duration-'))
    const props = durationKeys.map((k) => `--motion-${k}`)
    const lines = [HEADER_CSS]
    lines.push(`:root[data-motion='reduced'] {`)
    for (const p of props) lines.push(`  ${p}: 0ms;`)
    lines.push('}')
    lines.push(`@media (prefers-reduced-motion: reduce) {`)
    lines.push(`  :root {`)
    for (const p of props) lines.push(`    ${p}: 0ms;`)
    lines.push(`  }`)
    lines.push(`}`)
    lines.push('')
    write('motion-overrides.css', lines.join('\n'))
  }

  // ── custom-media.css ──────────────────────────────────────────────────────

  {
    const lines = [HEADER_CSS]
    for (const [key, value] of Object.entries(base.breakpoint ?? {})) {
      lines.push(`@custom-media --bp-${key} (min-width: ${value});`)
    }
    lines.push('')
    write('custom-media.css', lines.join('\n'))
  }

  // ── index.css ─────────────────────────────────────────────────────────────

  {
    const lines = [HEADER_CSS]
    lines.push(`@import './fonts.css';`)
    lines.push(`@import './base.css';`)
    for (const { stem } of ordered) lines.push(`@import './skin-${stem}.css';`)
    lines.push(`@import './motion-overrides.css';`)
    lines.push('')
    write('index.css', lines.join('\n'))
  }

  // ── skins.ts ──────────────────────────────────────────────────────────────

  {
    const defaultSemantic = defaultEntry.data.semantic ?? {}

    // SkinMeta objects
    const skinsLiteral = ordered
      .map(({ data }) => {
        const m = data.meta
        return (
          `  {\n` +
          `    name: '${escapeTs(m.name)}',\n` +
          `    label: '${escapeTs(m.label)}',\n` +
          `    era: '${escapeTs(m.era)}',\n` +
          `    colorScheme: '${m.colorScheme}',\n` +
          `    default: ${m.default === true},\n` +
          `    hidden: ${m.hidden === true},\n` +
          `    description: '${escapeTs(m.description ?? '')}',\n` +
          `  }`
        )
      })
      .join(',\n')

    const skinNamesLiteral = ordered.map(({ stem }) => `'${stem}'`).join(', ')

    // semanticTokens: CSS prop names from default skin in source order
    const semanticLiteral = SEMANTIC_NAMESPACES.map((ns) => {
      const keys = Object.keys(defaultSemantic[ns] ?? {})
      const props = keys.map((k) => `'--${ns}-${k}'`).join(', ')
      return `  ${ns}: [${props}]`
    }).join(',\n')

    // zones: names + overridden CSS prop names from default skin in source order
    const defaultZones = defaultEntry.data.zones ?? {}
    const zoneNamesLiteral = Object.keys(defaultZones)
      .map((z) => `'${z}'`)
      .join(', ')
    const zoneTokensLiteral = Object.entries(defaultZones)
      .map(([zoneName, zone]) => {
        const props = []
        for (const [ns, tokens] of Object.entries(zone.tokens ?? {})) {
          for (const key of Object.keys(tokens)) props.push(`'--${ns}-${key}'`)
        }
        return `  '${zoneName}': [${props.join(', ')}]`
      })
      .join(',\n')

    // baseTokens
    const spaceProps = Object.keys(base.space ?? {})
      .map((k) => `'--space-${k}'`)
      .join(', ')
    const zProps = Object.keys(base.z ?? {})
      .map((k) => `'--z-${k}'`)
      .join(', ')

    // breakpoints
    const bpLiteral = Object.entries(base.breakpoint ?? {})
      .map(([k, v]) => `  ${k}: '${v}'`)
      .join(',\n')

    let ts = `${HEADER_TS}\n\n`
    ts += `export interface SkinMeta {\n`
    ts += `  name: string; label: string; era: string\n`
    ts += `  colorScheme: 'light' | 'dark'\n`
    ts += `  default: boolean; hidden: boolean; description: string\n`
    ts += `}\n\n`
    ts += `export const skins: readonly SkinMeta[] = [\n${skinsLiteral},\n]\n\n`
    ts += `export const skinNames = [${skinNamesLiteral}] as const\n`
    ts += `export type SkinName = (typeof skinNames)[number]\n`
    ts += `export const defaultSkin: SkinMeta = skins.find((s) => s.default)!\n\n`
    ts += `export const semanticTokens: Record<\n`
    ts += `  'color' | 'radius' | 'type' | 'density' | 'motion' | 'shadow',\n`
    ts += `  readonly string[]\n`
    ts += `> = {\n${semanticLiteral},\n}\n\n`
    ts += `export const zoneNames = [${zoneNamesLiteral}] as const\n`
    ts += `export type ZoneName = (typeof zoneNames)[number]\n`
    ts += `export const zoneTokens: Record<ZoneName, readonly string[]> = {\n${
      zoneTokensLiteral ? zoneTokensLiteral + ',\n' : ''
    }}\n\n`
    ts += `export const baseTokens: Record<'space' | 'z', readonly string[]> = {\n`
    ts += `  space: [${spaceProps}],\n`
    ts += `  z: [${zProps}],\n`
    ts += `}\n\n`
    ts += `export const breakpoints: Record<string, string> = {\n${bpLiteral},\n}\n\n`
    ts += `export const SKIN_STORAGE_KEY = '${SKIN_STORAGE_KEY_VALUE}'\n`
    ts += `export const MOTION_STORAGE_KEY = '${MOTION_STORAGE_KEY_VALUE}'\n`

    write('skins.ts', ts)
  }

  // ── skins.json ────────────────────────────────────────────────────────────

  {
    const json = {
      default: defaultEntry.stem,
      storage: { skin: SKIN_STORAGE_KEY_VALUE, motion: MOTION_STORAGE_KEY_VALUE },
      skins: ordered.map(({ data }) => {
        const m = data.meta
        return {
          name: m.name,
          label: m.label,
          era: m.era,
          colorScheme: m.colorScheme,
          hidden: m.hidden === true,
          description: m.description ?? '',
          preloadFonts: (m.fonts ?? [])
            .filter((f) => f.preload === true)
            .map((f) => `fonts/${f.file}`),
        }
      }),
    }
    write('skins.json', JSON.stringify(json, null, 2) + '\n')
  }

  return { files: writtenFiles, warnings }
}

// ── CLI entry ──────────────────────────────────────────────────────────────

const isMain = process.argv[1] === fileURLToPath(import.meta.url)
if (isMain) {
  try {
    const result = buildTokens()
    for (const f of result.files) console.log('wrote', f)
    for (const w of result.warnings) console.warn('warning:', w)
  } catch (err) {
    console.error(err.message)
    process.exit(1)
  }
}
