// @vitest-environment node
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { buildTokens } from './build.mjs'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const TESTDATA = join(__dirname, 'testdata')

function fixture(name: string) {
  return join(TESTDATA, name)
}

function happyBuild(outDir: string) {
  return buildTokens({
    tokensDir: fixture('happy'),
    outDir,
    fontsDir: fixture('happy/fonts'),
  })
}

function read(outDir: string, name: string) {
  return readFileSync(join(outDir, name), 'utf8')
}

// ---------------------------------------------------------------------------
// Setup / teardown
// ---------------------------------------------------------------------------

let outDir: string

beforeEach(() => {
  outDir = mkdtempSync(join(tmpdir(), 'portfolio-tokens-'))
})

afterEach(() => {
  rmSync(outDir, { recursive: true, force: true })
})

// ---------------------------------------------------------------------------
// Happy path
// ---------------------------------------------------------------------------

describe('happy path', () => {
  it('returns non-empty files list and no warnings', () => {
    const result = happyBuild(outDir)
    expect(result.files.length).toBeGreaterThan(0)
    expect(result.warnings).toHaveLength(0)
  })

  it('base.css: emits :root with space and z tokens, no breakpoints', () => {
    happyBuild(outDir)
    const css = read(outDir, 'base.css')
    expect(css).toContain(':root {')
    expect(css).toContain('--space-0: 0;')
    expect(css).toContain('--space-1: 0.25rem;')
    expect(css).toContain('--z-base: 0;')
    expect(css).toContain('--z-raised: 10;')
    expect(css).not.toMatch(/--breakpoint/)
    expect(css).not.toMatch(/--bp-/)
    expect(css).toContain('GENERATED by ds/tokens/build.mjs')
  })

  it('skin-alpha.css: color-scheme, raw tokens, semantic tokens, refs resolved', () => {
    happyBuild(outDir)
    const css = read(outDir, 'skin-alpha.css')
    expect(css).toContain("[data-skin='alpha'] {")
    expect(css).toContain('color-scheme: light;')
    expect(css).toContain('--raw-color-white: #fff;')
    expect(css).toContain('--raw-color-black: #000;')
    expect(css).toContain('--color-surface: var(--raw-color-white);')
    expect(css).toContain('--color-ink: var(--raw-color-black);')
    expect(css).toContain('--radius-control: 4px;')
    expect(css).toContain('--type-body-size: 1rem;')
    expect(css).toContain('--density-gap: var(--space-1);')
    expect(css).toContain('--motion-duration-xs: 90ms;')
  })

  it('ref inside longer string compiles to var()', () => {
    happyBuild(outDir)
    const css = read(outDir, 'skin-alpha.css')
    // "raised": "0 1px 2px {raw.color.black}"
    expect(css).toContain('--shadow-raised: 0 1px 2px var(--raw-color-black);')
  })

  it('skin-alpha.css: zone block re-assigns semantic props under both selectors', () => {
    happyBuild(outDir)
    const css = read(outDir, 'skin-alpha.css')
    expect(css).toContain("[data-skin='alpha'] [data-zone='night'],")
    expect(css).toContain("[data-skin='alpha'][data-zone='night'] {")
    // zone block declares its own color-scheme and re-assigns the same semantic props
    const zoneBlock = css.slice(css.indexOf("[data-zone='night']"))
    expect(zoneBlock).toContain('color-scheme: dark;')
    expect(zoneBlock).toContain('--color-surface: var(--raw-color-black);')
    expect(zoneBlock).toContain('--color-ink: var(--raw-color-white);')
    expect(zoneBlock).toContain('--shadow-raised: 0 1px 2px var(--raw-color-white);')
  })

  it('skins.ts: zone exports from default skin', () => {
    happyBuild(outDir)
    const ts = read(outDir, 'skins.ts')
    expect(ts).toContain("export const zoneNames = ['night'] as const")
    expect(ts).toContain('export type ZoneName = (typeof zoneNames)[number]')
    expect(ts).toContain('export const zoneTokens: Record<ZoneName, readonly string[]>')
    expect(ts).toContain("'night': ['--color-surface', '--color-ink', '--shadow-raised']")
  })

  it('skin-beta.css: dark color-scheme, correct values', () => {
    happyBuild(outDir)
    const css = read(outDir, 'skin-beta.css')
    expect(css).toContain("[data-skin='beta'] {")
    expect(css).toContain('color-scheme: dark;')
    expect(css).toContain('--color-surface: var(--raw-color-dark);')
    expect(css).toContain('--color-ink: var(--raw-color-light);')
  })

  it('fonts.css: @font-face block with correct src path', () => {
    happyBuild(outDir)
    const css = read(outDir, 'fonts.css')
    expect(css).toContain('@font-face {')
    expect(css).toContain("font-family: 'Test Font';")
    expect(css).toContain("src: url('../../../assets/fonts/test.woff2') format('woff2');")
    expect(css).toContain('font-weight: 400;')
    expect(css).toContain('font-style: normal;')
    expect(css).toContain('font-display: swap;')
  })

  it('motion-overrides.css: zeroes duration-* under both selectors', () => {
    happyBuild(outDir)
    const css = read(outDir, 'motion-overrides.css')
    expect(css).toContain(":root[data-motion='reduced'] {")
    expect(css).toContain('--motion-duration-xs: 0ms;')
    expect(css).toContain('@media (prefers-reduced-motion: reduce) {')
    // should appear twice (once per block)
    const count = (css.match(/--motion-duration-xs: 0ms;/g) ?? []).length
    expect(count).toBe(2)
  })

  it('custom-media.css: @custom-media rules (no :root)', () => {
    happyBuild(outDir)
    const css = read(outDir, 'custom-media.css')
    expect(css).toContain('@custom-media --bp-sm (min-width: 640px);')
    expect(css).not.toContain(':root')
  })

  it('index.css: import order — fonts → base → skins (default first) → motion-overrides', () => {
    happyBuild(outDir)
    const css = read(outDir, 'index.css')
    const lines = css.split('\n').filter((l) => l.startsWith('@import'))
    expect(lines[0]).toBe("@import './fonts.css';")
    expect(lines[1]).toBe("@import './base.css';")
    expect(lines[2]).toBe("@import './skin-alpha.css';") // alpha is default
    expect(lines[3]).toBe("@import './skin-beta.css';")
    expect(lines[4]).toBe("@import './motion-overrides.css';")
    // custom-media.css must NOT be imported
    expect(css).not.toContain('custom-media')
  })

  it('skins.ts: pinned exports present and correct', () => {
    happyBuild(outDir)
    const ts = read(outDir, 'skins.ts')
    expect(ts).toContain('GENERATED by ds/tokens/build.mjs')
    expect(ts).toContain('export interface SkinMeta {')
    expect(ts).toContain('export const skins: readonly SkinMeta[]')
    expect(ts).toContain("export const skinNames = ['alpha', 'beta'] as const")
    expect(ts).toContain('export type SkinName = (typeof skinNames)[number]')
    expect(ts).toContain('export const defaultSkin: SkinMeta = skins.find((s) => s.default)!')
    expect(ts).toContain('export const semanticTokens:')
    expect(ts).toContain('export const baseTokens:')
    expect(ts).toContain('export const breakpoints:')
    expect(ts).toContain("export const SKIN_STORAGE_KEY = 'portfolio:skin'")
    expect(ts).toContain("export const MOTION_STORAGE_KEY = 'portfolio:motion'")
    // default skin (alpha) must appear first in skins array
    const alphaPos = ts.indexOf("name: 'alpha'")
    const betaPos = ts.indexOf("name: 'beta'")
    expect(alphaPos).toBeLessThan(betaPos)
    // semantic tokens include CSS prop names
    expect(ts).toContain("'--color-surface'")
    expect(ts).toContain("'--radius-control'")
    // base tokens
    expect(ts).toContain("'--space-0'")
    expect(ts).toContain("'--z-base'")
    // breakpoints
    expect(ts).toContain("sm: '640px'")
  })

  it('skins.json: pinned shape', () => {
    happyBuild(outDir)
    const json = JSON.parse(read(outDir, 'skins.json'))
    expect(json.default).toBe('alpha')
    expect(json.storage).toEqual({ skin: 'portfolio:skin', motion: 'portfolio:motion' })
    expect(json.skins).toHaveLength(2)
    const alpha = json.skins[0]
    expect(alpha.name).toBe('alpha')
    expect(alpha.colorScheme).toBe('light')
    expect(alpha.hidden).toBe(false)
    expect(alpha.preloadFonts).toEqual(['fonts/test.woff2'])
    const beta = json.skins[1]
    expect(beta.name).toBe('beta')
    expect(beta.colorScheme).toBe('dark')
    expect(beta.hidden).toBe(true)
    expect(beta.preloadFonts).toEqual([])
  })

  it('deterministic: two runs produce byte-identical output', () => {
    happyBuild(outDir)

    const outDir2 = mkdtempSync(join(tmpdir(), 'portfolio-tokens-'))
    try {
      buildTokens({
        tokensDir: fixture('happy'),
        outDir: outDir2,
        fontsDir: fixture('happy/fonts'),
      })
      for (const name of [
        'base.css',
        'skin-alpha.css',
        'skin-beta.css',
        'fonts.css',
        'motion-overrides.css',
        'custom-media.css',
        'index.css',
        'skins.ts',
        'skins.json',
      ]) {
        expect(read(outDir, name)).toBe(read(outDir2, name))
      }
    } finally {
      rmSync(outDir2, { recursive: true, force: true })
    }
  })
})

// ---------------------------------------------------------------------------
// Failure cases
// ---------------------------------------------------------------------------

describe('failure cases', () => {
  function fails(tokensDir: string, fontsDir?: string): string {
    expect(() =>
      buildTokens({
        tokensDir: fixture(tokensDir),
        outDir,
        fontsDir: fontsDir ? fixture(fontsDir) : fixture('happy/fonts'),
      }),
    ).toThrow()
    let msg = ''
    try {
      buildTokens({
        tokensDir: fixture(tokensDir),
        outDir,
        fontsDir: fontsDir ? fixture(fontsDir) : fixture('happy/fonts'),
      })
    } catch (e) {
      msg = (e as Error).message
    }
    return msg
  }

  it('missing semantic key in one skin names the offender', () => {
    const msg = fails('missing-key')
    expect(msg).toContain('beta.tokens.json')
    expect(msg).toContain('ink')
    expect(msg).toContain('missing key')
  })

  it('unresolved raw ref names the bad ref', () => {
    const msg = fails('bad-ref')
    expect(msg).toContain('nonexistent')
    expect(msg).toContain('alpha.tokens.json')
  })

  it('two defaults reports the duplicate', () => {
    const msg = fails('two-defaults')
    expect(msg).toMatch(/2 skins have default: true/)
  })

  it('zero defaults reports the missing default', () => {
    const msg = fails('no-defaults')
    expect(msg).toContain('No skin has default: true')
  })

  it('invalid colorScheme names the bad value', () => {
    const msg = fails('bad-color-scheme')
    expect(msg).toContain('purple')
    expect(msg).toContain('colorScheme')
  })

  it('missing font file names the file', () => {
    const msg = fails('missing-font', 'missing-font/fonts')
    expect(msg).toContain('does-not-exist.woff2')
  })

  it('non-kebab key names the offender', () => {
    const msg = fails('bad-key')
    expect(msg).toContain('BadKey')
    expect(msg).toContain('kebab-case')
  })

  it('extra semantic namespace names the offender', () => {
    const msg = fails('extra-namespace')
    expect(msg).toContain('custom')
    expect(msg).toContain('extra semantic namespace')
  })

  it('zone re-assigning a nonexistent semantic key names the offender', () => {
    const msg = fails('zone-unknown-key')
    expect(msg).toContain('zones.night.color.phantom')
    expect(msg).toContain('may only re-assign existing semantic keys')
  })

  it('zone value with unresolved raw ref names the bad ref', () => {
    const msg = fails('zone-bad-ref')
    expect(msg).toContain('zones.night.color.surface')
    expect(msg).toContain('{raw.color.void}')
  })

  it('zone missing from one skin fails parity and names both files', () => {
    const msg = fails('zone-parity')
    expect(msg).toContain('beta.tokens.json')
    expect(msg).toContain("missing zone 'night'")
    expect(msg).toContain('alpha.tokens.json')
  })
})

// ---------------------------------------------------------------------------
// Warning case
// ---------------------------------------------------------------------------

describe('warning case', () => {
  it('unreferenced raw key returns a warning and build still succeeds', () => {
    const result = buildTokens({
      tokensDir: fixture('warn-unreferenced'),
      outDir,
      fontsDir: fixture('happy/fonts'),
    })
    expect(result.warnings.length).toBeGreaterThan(0)
    const w = result.warnings.join('\n')
    expect(w).toContain('unused')
    // build still succeeds — output files were written
    expect(result.files.length).toBeGreaterThan(0)
  })
})
